import React from 'react';

const ComboDatas = [
    {
        name: "UFO Sightings",
        description: "Data related to reported UFO sightings over time.",
        dataKey: "ufo_sightings_data",
        id:1
    },
    {
        name: "Divorce Rates",
        description: "Annual divorce rates per 1,000 people in a specific region.",
        dataKey: "divorce_rates_data",
        id:2
    },
    {
        name: "Per Capita Cheese Consumption",
        description: "Average amount of cheese consumed per person each year.",
        dataKey: "cheese_consumption_data",
        id:3
    },
    {
        name: "Worldwide Spider Population",
        description: "Estimated population of spiders across the globe.",
        dataKey: "spider_population_data",
        id:4
    },
    {
        name: "Number of People Who Drowned in a Swimming Pool",
        description: "Annual statistics on drowning deaths in swimming pools.",
        dataKey: "drowning_deaths_data",
        id:5
    },
    {
        name: "Power Generated by Wind Turbines",
        description: "The amount of electricity generated by wind turbines per year.",
        dataKey: "wind_power_data",
        id:6
    },
];

export default ComboDatas;